server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monitoring
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true